sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t udemy/production-grade-workflow-image -f Dockerfile.dev .

script:
  - docker run -e CI=true udemy/production-grade-workflow-image npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "udemy-docker-dev-workflow"
  env: "UdemyDockerDevWorkflow-env"
  bucket_name: "elasticbeanstalk-us-east-1-803782810527"
  bucket_path: "udemy-docker-dev-workflow"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"